AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Resources:

  Magic8Ball:
    Type: AWS::Serverless::Function
    Properties:
      Handler: magic8ball.lambda_handler
      Runtime: python3.9
      Events:
        RestAPI:
          Type: Api
          Properties:
            Path: /magic8ball
            Method: ANY
